<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.Pricing.Domain</RootNamespace>
    <AssemblyName>Tooba.Pricing.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Offer\Tooba.Offer.Domain\Tooba.Offer.Domain.csproj" />
  </ItemGroup>
</Project>
