<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.Order.Contracts</RootNamespace>
    <AssemblyName>Tooba.Order.Contracts</AssemblyName>
  </PropertyGroup>
</Project>
