<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.Notification.Application</RootNamespace>
    <AssemblyName>Tooba.Notification.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Tooba.Notification.Domain\Tooba.Notification.Domain.csproj" />
  </ItemGroup>
</Project>
