import type { ResponsiveContract } from "./types.ts";

/** Code-owned responsive contracts. Admin never configures breakpoints. */
export const RESPONSIVE_CONTRACTS: Record<string, ResponsiveContract> = {
  "hero.full-width": {
    variantKey: "hero.full-width",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "Large", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "1", tablet: "1", mobile: "1" },
    notesFa: "اسلاید تمام‌عرض؛ موبایل ارتفاع محدود سیستم.",
  },
  "hero.contained": {
    variantKey: "hero.contained",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "Medium", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "1", tablet: "1", mobile: "1" },
    notesFa: "اسلاید داخل کانتینر با گوشه گرد.",
  },
  "hero.split": {
    variantKey: "hero.split",
    columns: { desktop: "2", tablet: "2", mobile: "1" },
    height: { desktop: "Large", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "1", tablet: "1", mobile: "1" },
    notesFa: "دو ستون دسکتاپ؛ موبایل پشته.",
  },
  "hero.side-promos": {
    variantKey: "hero.side-promos",
    columns: { desktop: "3", tablet: "2", mobile: "1" },
    height: { desktop: "Large", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "1+2", tablet: "1+1", mobile: "1" },
    notesFa: "هیرو + پروموی کناری؛ موبایل فقط هیرو.",
  },
  "hero.editorial": {
    variantKey: "hero.editorial",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "ExtraLarge", tablet: "Large", mobile: "Medium" },
    itemVisible: { desktop: "1", tablet: "1", mobile: "1" },
    notesFa: "هیرو تحریریه با کپشن قوی.",
  },
  "story.circle": {
    variantKey: "story.circle",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "8-12", tablet: "6-8", mobile: "4-6" },
    notesFa: "دایره‌های استوری افقی.",
  },
  "story.image-circles": {
    variantKey: "story.image-circles",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "8-12", tablet: "6-8", mobile: "4-6" },
    notesFa: "دایره با تصویر کامل.",
  },
  "story.rounded-cards": {
    variantKey: "story.rounded-cards",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "Medium", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "6-8", tablet: "4-6", mobile: "3-4" },
    notesFa: "کارت‌های گرد میانبر.",
  },
  "story.icon-shortcuts": {
    variantKey: "story.icon-shortcuts",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "8-12", tablet: "6-8", mobile: "4-6" },
    notesFa: "میانبر آیکونی.",
  },
  "category.image-cards": {
    variantKey: "category.image-cards",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "Medium", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "5-7", tablet: "3-5", mobile: "2-3" },
    notesFa: "کارت دسته با تصویر.",
  },
  "category.compact-tiles": {
    variantKey: "category.compact-tiles",
    columns: { desktop: "6", tablet: "4", mobile: "3" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "12", tablet: "8", mobile: "6" },
    notesFa: "کاشی فشرده.",
  },
  "category.horizontal-rail": {
    variantKey: "category.horizontal-rail",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "6-8", tablet: "4-6", mobile: "3-4" },
    notesFa: "ریل افقی دسته.",
  },
  "category.editorial-tiles": {
    variantKey: "category.editorial-tiles",
    columns: { desktop: "4", tablet: "2", mobile: "1" },
    height: { desktop: "Large", tablet: "Medium", mobile: "Medium" },
    itemVisible: { desktop: "4", tablet: "2", mobile: "1" },
    notesFa: "کاشی تحریریه.",
  },
  "product.card-carousel": {
    variantKey: "product.card-carousel",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "4-5", tablet: "3", mobile: "2" },
    notesFa: "اسلایدر کارت کالا.",
  },
  "product.grid": {
    variantKey: "product.grid",
    columns: { desktop: "4", tablet: "3", mobile: "2" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "8-12", tablet: "6-9", mobile: "4-6" },
    notesFa: "شبکه کالا.",
  },
  "product.compact-rows": {
    variantKey: "product.compact-rows",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "6-10", tablet: "5-8", mobile: "4-6" },
    notesFa: "ردیف فشرده.",
  },
  "product.category-columns": {
    variantKey: "product.category-columns",
    columns: { desktop: "3-4", tablet: "2", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "per-col 3", tablet: "per-col 3", mobile: "rail" },
    notesFa: "ستون‌های دسته‌ای پرفروش.",
  },
  "product.featured-plus-rail": {
    variantKey: "product.featured-plus-rail",
    columns: { desktop: "1+rail", tablet: "1+rail", mobile: "stack" },
    height: { desktop: "Large", tablet: "Medium", mobile: "auto" },
    itemVisible: { desktop: "1+4", tablet: "1+3", mobile: "1+2" },
    notesFa: "ویژه + ریل.",
  },
  "product.tabbed": {
    variantKey: "product.tabbed",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "4-5", tablet: "3", mobile: "2" },
    notesFa: "تب‌های کالا.",
  },
  "product.large-cards": {
    variantKey: "product.large-cards",
    columns: { desktop: "3", tablet: "2", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "3-6", tablet: "2-4", mobile: "1-3" },
    notesFa: "کارت بزرگ.",
  },
  "product.minimal-list": {
    variantKey: "product.minimal-list",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "8-12", tablet: "6-10", mobile: "5-8" },
    notesFa: "فهرست مینیمال.",
  },
  "ranked.horizontal": {
    variantKey: "ranked.horizontal",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "5-7", tablet: "3-5", mobile: "2-3" },
    notesFa: "رتبه‌بندی افقی.",
  },
  "ranked.grid": {
    variantKey: "ranked.grid",
    columns: { desktop: "4", tablet: "3", mobile: "2" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "8", tablet: "6", mobile: "4" },
    notesFa: "شبکه رتبه‌دار.",
  },
  "ranked.ticker": {
    variantKey: "ranked.ticker",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "1", tablet: "1", mobile: "1" },
    notesFa: "تیکر فشرده.",
  },
  "ranked.multi-column": {
    variantKey: "ranked.multi-column",
    columns: { desktop: "3", tablet: "2", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "9", tablet: "6", mobile: "4" },
    notesFa: "چند ستون رتبه.",
  },
  "banner.single": {
    variantKey: "banner.single",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "Medium", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "1", tablet: "1", mobile: "1" },
    notesFa: "بنر تکی.",
  },
  "banner.two-equal": {
    variantKey: "banner.two-equal",
    columns: { desktop: "2", tablet: "2", mobile: "1" },
    height: { desktop: "Medium", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "2", tablet: "2", mobile: "2" },
    notesFa: "دو بنر مساوی.",
  },
  "banner.two-asymmetric": {
    variantKey: "banner.two-asymmetric",
    columns: { desktop: "2", tablet: "2", mobile: "1" },
    height: { desktop: "Medium", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "2", tablet: "2", mobile: "2" },
    notesFa: "دو بنر نامتقارن.",
  },
  "banner.three": {
    variantKey: "banner.three",
    columns: { desktop: "3", tablet: "3", mobile: "1" },
    height: { desktop: "Medium", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "3", tablet: "3", mobile: "3" },
    notesFa: "سه بنر.",
  },
  "banner.four-grid": {
    variantKey: "banner.four-grid",
    columns: { desktop: "2x2", tablet: "2x2", mobile: "1" },
    height: { desktop: "Medium", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "4", tablet: "4", mobile: "4" },
    notesFa: "شبکه ۴ تایی.",
  },
  "banner.one-large-two-small": {
    variantKey: "banner.one-large-two-small",
    columns: { desktop: "mosaic", tablet: "stack", mobile: "stack" },
    height: { desktop: "Large", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "3", tablet: "3", mobile: "3" },
    notesFa: "یک بزرگ دو کوچک.",
  },
  "banner.one-large-four-small": {
    variantKey: "banner.one-large-four-small",
    columns: { desktop: "mosaic", tablet: "stack", mobile: "stack" },
    height: { desktop: "Large", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "5", tablet: "5", mobile: "5" },
    notesFa: "یک بزرگ چهار کوچک.",
  },
  "banner.eight-compact": {
    variantKey: "banner.eight-compact",
    columns: { desktop: "4x2", tablet: "4x2", mobile: "2x4" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "8", tablet: "8", mobile: "8" },
    notesFa: "هشت فشرده.",
  },
  "banner.mosaic-2x2": {
    variantKey: "banner.mosaic-2x2",
    columns: { desktop: "2x2", tablet: "2x2", mobile: "1" },
    height: { desktop: "Medium", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "4", tablet: "4", mobile: "4" },
    notesFa: "موزاییک ۲×۲.",
  },
  "brand.logo-rail": {
    variantKey: "brand.logo-rail",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "8-12", tablet: "6-8", mobile: "4-6" },
    notesFa: "ریل لوگو.",
  },
  "brand.logo-grid": {
    variantKey: "brand.logo-grid",
    columns: { desktop: "6", tablet: "4", mobile: "3" },
    height: { desktop: "Compact", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "12", tablet: "8", mobile: "6" },
    notesFa: "شبکه لوگو.",
  },
  "brand.featured": {
    variantKey: "brand.featured",
    columns: { desktop: "3", tablet: "2", mobile: "1" },
    height: { desktop: "Medium", tablet: "Medium", mobile: "Compact" },
    itemVisible: { desktop: "3-6", tablet: "2-4", mobile: "1-3" },
    notesFa: "برند ویژه.",
  },
  "reviews.card-carousel": {
    variantKey: "reviews.card-carousel",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "3", tablet: "2", mobile: "1" },
    notesFa: "اسلایدر نظر.",
  },
  "reviews.compact-quotes": {
    variantKey: "reviews.compact-quotes",
    columns: { desktop: "3", tablet: "2", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "3-6", tablet: "2-4", mobile: "1-3" },
    notesFa: "نقل فشرده.",
  },
  "article.magazine-rail": {
    variantKey: "article.magazine-rail",
    columns: { desktop: "rail", tablet: "rail", mobile: "rail" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "3-4", tablet: "2-3", mobile: "1-2" },
    notesFa: "ریل مجله.",
  },
  "article.grid": {
    variantKey: "article.grid",
    columns: { desktop: "3", tablet: "2", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "6", tablet: "4", mobile: "3" },
    notesFa: "شبکه مقاله.",
  },
  "article.featured-plus-list": {
    variantKey: "article.featured-plus-list",
    columns: { desktop: "1+list", tablet: "stack", mobile: "stack" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "1+4", tablet: "1+3", mobile: "1+2" },
    notesFa: "ویژه + فهرست.",
  },
  "promo.default": {
    variantKey: "promo.default",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "Medium", tablet: "Compact", mobile: "Compact" },
    itemVisible: { desktop: "1", tablet: "1", mobile: "1" },
    notesFa: "پروموی تکی کنترل‌شده.",
  },
  "richtext.default": {
    variantKey: "richtext.default",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "1", tablet: "1", mobile: "1" },
    notesFa: "متن ساده بدون قالب‌بندی خام.",
  },
  "nav.menu": {
    variantKey: "nav.menu",
    columns: { desktop: "1", tablet: "1", mobile: "1" },
    height: { desktop: "auto", tablet: "auto", mobile: "auto" },
    itemVisible: { desktop: "menu", tablet: "menu", mobile: "menu" },
    notesFa: "منوی فعال فروشگاه.",
  },
};

export function requireResponsiveContract(variantKey: string): ResponsiveContract {
  const contract = RESPONSIVE_CONTRACTS[variantKey];
  if (!contract) throw new Error(`Missing responsive contract: ${variantKey}`);
  return contract;
}
