// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tooba.Catalog.Infrastructure.Persistence;

#nullable disable

namespace Tooba.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogAttributeDefinition", b =>
                {
                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVariantAxis")
                        .HasColumnType("boolean")
                        .HasColumnName("is_variant_axis");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value_kind");

                    b.HasKey("DefinitionId")
                        .HasName("pk_attribute_definitions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_attribute_definitions_code");

                    b.ToTable("attribute_definitions", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogAttributeOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.HasKey("OptionId")
                        .HasName("pk_attribute_options");

                    b.HasIndex("DefinitionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_attribute_options_definition_id_code");

                    b.ToTable("attribute_options", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogBrand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SlugSeam")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug_seam");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BrandId")
                        .HasName("pk_brands");

                    b.ToTable("brands", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogLocalizedText", b =>
                {
                    b.Property<Guid>("TextId")
                        .HasColumnType("uuid")
                        .HasColumnName("text_id");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field_key");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("locale");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("owner_kind");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("value");

                    b.HasKey("TextId")
                        .HasName("pk_localized_texts");

                    b.HasIndex("OwnerKind", "OwnerId", "FieldKey", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_localized_texts_owner_kind_owner_id_field_key_locale");

                    b.ToTable("localized_texts", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("SeoTitleSeam")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("seo_title_seam");

                    b.Property<string>("SlugSeam")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug_seam");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProductId")
                        .HasName("pk_products");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_products_brand_id");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogProductAttributeValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("value_id");

                    b.Property<string>("CanonicalValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("canonical_value");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("ValueId")
                        .HasName("pk_product_attribute_values");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("ix_product_attribute_values_definition_id");

                    b.HasIndex("ProductId", "DefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_attribute_values_product_id_definition_id");

                    b.ToTable("product_attribute_values", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogProductCategory", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("AssignmentId")
                        .HasName("pk_product_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_categories_category_id");

                    b.HasIndex("ProductId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_categories_product_id_category_id");

                    b.ToTable("product_categories", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogProductMediaReference", b =>
                {
                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("ReferenceId")
                        .HasName("pk_product_media_references");

                    b.HasIndex("ProductId", "MediaAssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_media_references_product_id_media_asset_id");

                    b.ToTable("product_media_references", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogVariant", b =>
                {
                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("CatalogCodeSeam")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalog_code_seam");

                    b.Property<string>("CombinationFingerprint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("combination_fingerprint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VariantId")
                        .HasName("pk_variants");

                    b.HasIndex("ProductId", "CombinationFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_variants_product_id_combination_fingerprint");

                    b.ToTable("variants", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogVariantAttributeValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("value_id");

                    b.Property<string>("CanonicalValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("canonical_value");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("ValueId")
                        .HasName("pk_variant_attribute_values");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("ix_variant_attribute_values_definition_id");

                    b.HasIndex("VariantId", "DefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_variant_attribute_values_variant_id_definition_id");

                    b.ToTable("variant_attribute_values", "catalog");
                });

            modelBuilder.Entity("Tooba.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("edition");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "catalog");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogAttributeOption", b =>
                {
                    b.HasOne("Tooba.Catalog.Domain.CatalogAttributeDefinition", null)
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_options_attribute_definitions_definition_id");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogCategory", b =>
                {
                    b.HasOne("Tooba.Catalog.Domain.CatalogCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogProduct", b =>
                {
                    b.HasOne("Tooba.Catalog.Domain.CatalogBrand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_products_brands_brand_id");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogProductAttributeValue", b =>
                {
                    b.HasOne("Tooba.Catalog.Domain.CatalogAttributeDefinition", null)
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_attribute_values_attribute_definitions_definition_id");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogProductCategory", b =>
                {
                    b.HasOne("Tooba.Catalog.Domain.CatalogCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_categories_category_id");

                    b.HasOne("Tooba.Catalog.Domain.CatalogProduct", null)
                        .WithMany("CategoryAssignments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_products_product_id");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogVariant", b =>
                {
                    b.HasOne("Tooba.Catalog.Domain.CatalogProduct", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variants_products_product_id");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogVariantAttributeValue", b =>
                {
                    b.HasOne("Tooba.Catalog.Domain.CatalogAttributeDefinition", null)
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_variant_attribute_values_attribute_definitions_definition_id");

                    b.HasOne("Tooba.Catalog.Domain.CatalogVariant", null)
                        .WithMany("AttributeValues")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variant_attribute_values_variants_variant_id");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogProduct", b =>
                {
                    b.Navigation("CategoryAssignments");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Tooba.Catalog.Domain.CatalogVariant", b =>
                {
                    b.Navigation("AttributeValues");
                });
#pragma warning restore 612, 618
        }
    }
}
