// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tooba.AccessControl.Infrastructure.Persistence;

#nullable disable

namespace Tooba.AccessControl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20260827140753_InitialAccessControl")]
    partial class InitialAccessControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access_control")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tooba.AccessControl.Domain.AccessAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("after_summary");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("BeforeSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("before_summary");

                    b.Property<Guid?>("SellerScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_scope_id");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_access_audit_events");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_access_audit_events_at");

                    b.HasIndex("SellerScopeId", "At")
                        .HasDatabaseName("ix_access_audit_events_seller_scope_id_at");

                    b.ToTable("access_audit_events", "access_control");
                });

            modelBuilder.Entity("Tooba.AccessControl.Domain.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsMutable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mutable");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_scope_id");

                    b.Property<int>("OwnerScopeKind")
                        .HasColumnType("integer")
                        .HasColumnName("owner_scope_kind");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("OwnerScopeKind", "OwnerScopeId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_owner_scope_kind_owner_scope_id_code");

                    b.HasIndex("OwnerScopeKind", "OwnerScopeId", "IsArchived")
                        .HasDatabaseName("ix_roles_owner_scope_kind_owner_scope_id_is_archived");

                    b.ToTable("roles", "access_control");
                });

            modelBuilder.Entity("Tooba.AccessControl.Domain.PlatformSellerCeiling", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("SellerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_party_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_platform_seller_ceilings");

                    b.HasIndex("SellerPartyId")
                        .HasDatabaseName("ix_platform_seller_ceilings_seller_party_id");

                    b.HasIndex("SellerPartyId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_seller_ceilings_seller_party_id_permission_id");

                    b.ToTable("platform_seller_ceilings", "access_control");
                });

            modelBuilder.Entity("Tooba.AccessControl.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<int>("ScopeKind")
                        .HasColumnType("integer")
                        .HasColumnName("scope_kind");

                    b.Property<Guid?>("ScopeResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_resource_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permissions_role_id");

                    b.HasIndex("RoleId", "PermissionId", "ScopeKind", "ScopeResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_permissions_role_id_permission_id_scope_kind_scope_res");

                    b.ToTable("role_permissions", "access_control");
                });

            modelBuilder.Entity("Tooba.AccessControl.Domain.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("OwnerScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_scope_id");

                    b.Property<int>("OwnerScopeKind")
                        .HasColumnType("integer")
                        .HasColumnName("owner_scope_kind");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role_assignments");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_assignments_role_id");

                    b.HasIndex("OwnerScopeKind", "OwnerScopeId", "UserId")
                        .HasDatabaseName("ix_user_role_assignments_owner_scope_kind_owner_scope_id_user_");

                    b.HasIndex("UserId", "RoleId", "OwnerScopeKind", "OwnerScopeId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_assignments_user_id_role_id_owner_scope_kind_owne");

                    b.ToTable("user_role_assignments", "access_control");
                });

            modelBuilder.Entity("Tooba.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("edition");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "access_control");
                });
#pragma warning restore 612, 618
        }
    }
}
