using System.Text.Json;
using System.Text.RegularExpressions;

namespace Tooba.Host.Tests;

/// <summary>
/// Hand-written source-size freeze helpers for TMAR ARCH-SIZE-* guards.
/// </summary>
internal static class TmarSourceSizeGuard
{
    public const int NewFileLocThreshold = 800;

    private static readonly HashSet<string> SourceExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".cs", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".go", ".rs", ".java", ".kt", ".sql", ".ps1", ".sh",
    };

    private static readonly HashSet<string> ExcludedDirNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "node_modules", "bin", "obj", ".git", ".vs", "dist", "build", ".next", "coverage",
        "vendor", "packages", "artifacts", "App_Data", "tmp", ".tmp",
    };

    public sealed record SourceFileInfo(string Path, string Language, int PhysicalLoc, string Classification);

    public sealed record Violation(string Path, int CurrentLoc, int? BaselineLoc, int Threshold, string ViolationType);

    public static string Classify(string language, int loc)
    {
        var isFe = language is "ts" or "tsx" or "js" or "jsx";
        if (isFe)
        {
            if (loc > 1200) return "CRITICAL_GOD_FILE";
            if (loc > 800) return "OVERSIZED_LEGACY";
            if (loc > 500) return "WATCH";
            return "NORMAL";
        }

        if (loc > 1500) return "CRITICAL_GOD_FILE";
        if (loc > 800) return "OVERSIZED_LEGACY";
        if (loc > 500) return "WATCH";
        return "NORMAL";
    }

    public static int CountPhysicalLoc(string text) =>
        text.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None).Length;

    public static bool ShouldExcludeRelativePath(string relativePath)
    {
        var n = relativePath.Replace('\\', '/');
        if (n.Contains("/Migrations/", StringComparison.OrdinalIgnoreCase) && n.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (Regex.IsMatch(n, @"ModelSnapshot\.cs$", RegexOptions.IgnoreCase))
        {
            return true;
        }

        if (Regex.IsMatch(n, @"\.g\.cs$", RegexOptions.IgnoreCase) || Regex.IsMatch(n, @"\.generated\.", RegexOptions.IgnoreCase))
        {
            return true;
        }

        if (n.Contains("/wwwroot/lib/", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (n.Contains("/docs/evidence/", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (n.EndsWith(".min.js", StringComparison.OrdinalIgnoreCase) || n.EndsWith(".min.css", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (n.EndsWith("package-lock.json", StringComparison.OrdinalIgnoreCase)
            || n.EndsWith("yarn.lock", StringComparison.OrdinalIgnoreCase)
            || n.EndsWith("pnpm-lock.yaml", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        // Ephemeral local helper scripts (not product source).
        if (Path.GetFileName(n).StartsWith(".tmp-", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return false;
    }

    public static bool LooksGenerated(string text)
    {
        var head = text.Length > 800 ? text[..800] : text;
        return head.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
               || head.Contains("This code was generated by a tool", StringComparison.OrdinalIgnoreCase);
    }

    public static IReadOnlyList<SourceFileInfo> ScanHandWrittenSources(string repoRoot)
    {
        var results = new List<SourceFileInfo>();
        Walk(repoRoot, repoRoot, results);
        return results;
    }

    private static void Walk(string repoRoot, string dir, List<SourceFileInfo> acc)
    {
        foreach (var entry in Directory.EnumerateFileSystemEntries(dir))
        {
            var name = Path.GetFileName(entry);
            if (Directory.Exists(entry))
            {
                if (ExcludedDirNames.Contains(name))
                {
                    continue;
                }

                Walk(repoRoot, entry, acc);
                continue;
            }

            var ext = Path.GetExtension(entry);
            if (!SourceExtensions.Contains(ext))
            {
                continue;
            }

            var rel = Path.GetRelativePath(repoRoot, entry).Replace('\\', '/');
            if (ShouldExcludeRelativePath(rel))
            {
                continue;
            }

            string text;
            try
            {
                text = File.ReadAllText(entry);
            }
            catch
            {
                continue;
            }

            if (LooksGenerated(text))
            {
                continue;
            }

            var loc = CountPhysicalLoc(text);
            var language = ext.TrimStart('.').ToLowerInvariant();
            acc.Add(new SourceFileInfo(rel, language, loc, Classify(language, loc)));
        }
    }

    public static IReadOnlyList<Violation> Evaluate(IEnumerable<SourceFileInfo> actualFiles, JsonElement baselineRoot)
    {
        var threshold = baselineRoot.TryGetProperty("thresholdNewFileLoc", out var thr)
            ? thr.GetInt32()
            : NewFileLocThreshold;

        var baselineEntries = baselineRoot.GetProperty("files").EnumerateArray()
            .Select(e => (
                Path: e.GetProperty("path").GetString()!,
                Loc: e.GetProperty("loc").GetInt32(),
                Classification: e.GetProperty("classification").GetString()!))
            .ToDictionary(x => x.Path, x => x, StringComparer.OrdinalIgnoreCase);

        var actual = actualFiles.ToDictionary(f => f.Path, f => f, StringComparer.OrdinalIgnoreCase);
        var violations = new List<Violation>();

        foreach (var (path, entry) in baselineEntries)
        {
            if (!actual.TryGetValue(path, out var file))
            {
                violations.Add(new Violation(path, 0, entry.Loc, threshold, "BASELINE_ENTRY_MISSING_FILE"));
                continue;
            }

            if (file.PhysicalLoc > entry.Loc)
            {
                violations.Add(new Violation(path, file.PhysicalLoc, entry.Loc, threshold, "OVERSIZED_GROWTH"));
            }
        }

        foreach (var (path, file) in actual)
        {
            if (baselineEntries.ContainsKey(path))
            {
                continue;
            }

            if (file.PhysicalLoc > threshold)
            {
                violations.Add(new Violation(path, file.PhysicalLoc, null, threshold, "NEW_OVERSIZED_FILE"));
            }
        }

        return violations;
    }
}
