<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <RootNamespace>Tooba.CustomerProfile.Application</RootNamespace>
    <AssemblyName>Tooba.CustomerProfile.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Tooba.CustomerProfile.Domain\Tooba.CustomerProfile.Domain.csproj" />
    <ProjectReference Include="..\Tooba.CustomerProfile.Contracts\Tooba.CustomerProfile.Contracts.csproj" />
    <ProjectReference Include="..\..\Order\Tooba.Order.Contracts\Tooba.Order.Contracts.csproj" />
    <ProjectReference Include="..\..\Wishlist\Tooba.Wishlist.Contracts\Tooba.Wishlist.Contracts.csproj" />
    <ProjectReference Include="..\..\AddressBook\Tooba.AddressBook.Contracts\Tooba.AddressBook.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\Tooba.Identity.Contracts\Tooba.Identity.Contracts.csproj" />
  </ItemGroup>
</Project>
