<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.Offer.Application</RootNamespace>
    <AssemblyName>Tooba.Offer.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Catalog\Tooba.Catalog.Contracts\Tooba.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\Party\Tooba.Party.Contracts\Tooba.Party.Contracts.csproj" />
    <ProjectReference Include="..\Tooba.Offer.Domain\Tooba.Offer.Domain.csproj" />
    <ProjectReference Include="..\Tooba.Offer.Contracts\Tooba.Offer.Contracts.csproj" />
  </ItemGroup>
</Project>
