<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.Offer.Endpoints</RootNamespace>
    <AssemblyName>Tooba.Offer.Endpoints</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tooba.Offer.Application\Tooba.Offer.Application.csproj" />
    <ProjectReference Include="..\Tooba.Offer.Contracts\Tooba.Offer.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
