// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tooba.PlatformProbe.Infrastructure.Persistence;

#nullable disable

namespace Tooba.PlatformProbe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformProbeDbContext))]
    [Migration("20260823000054_InitialPlatformProbe")]
    partial class InitialPlatformProbe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform_probe")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tooba.PlatformProbe.Infrastructure.Persistence.PlatformProbeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExternalReference")
                        .HasColumnType("uuid")
                        .HasColumnName("external_reference");

                    b.HasKey("Id")
                        .HasName("pk_probe_records");

                    b.ToTable("probe_records", "platform_probe");
                });
#pragma warning restore 612, 618
        }
    }
}
