<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <RootNamespace>Tooba.Support.Endpoints</RootNamespace>
    <AssemblyName>Tooba.Support.Endpoints</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\SupportErrors.resx"><Generator></Generator></EmbeddedResource>
    <EmbeddedResource Update="Resources\SupportErrors.fa.resx"><Generator></Generator></EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tooba.Support.Application\Tooba.Support.Application.csproj" />
    <ProjectReference Include="..\Tooba.Support.Contracts\Tooba.Support.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
