using Microsoft.AspNetCore.Http;
using Tooba.BuildingBlocks.Presentation.Errors;
using Tooba.Fulfillment.Contracts.Errors;

namespace Tooba.Fulfillment.Infrastructure.Errors;

/// <summary>
/// Explicit error catalog for every stable Fulfillment-owned semantic code.
/// Duplicate usage is allowed; duplicate descriptor ownership is not — this is the single
/// owner of the `fulfillment.*`, `shipping_service.*` and `shipping_service_option.*` keyspaces
/// plus the seller/customer authorization codes Fulfillment emits at its own boundary.
/// </summary>
public sealed class FulfillmentErrorCatalogContributor : IErrorCatalogContributor
{
    /// <inheritdoc />
    public IReadOnlyList<ErrorDescriptor> Contribute() =>
    [
        D(FulfillmentErrorCodes.Missing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Fulfillment was not found."),
        D(FulfillmentErrorCodes.NotFound, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Fulfillment was not found."),
        D(FulfillmentErrorCodes.Rejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Fulfillment mutation was rejected."),
        D(FulfillmentErrorCodes.OrderNotFound, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Source order was not found."),
        D(FulfillmentErrorCodes.OrderNotPaid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Source order is not paid."),
        D(FulfillmentErrorCodes.OrderLineNotFound, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Order line was not found."),
        D(FulfillmentErrorCodes.QuantityPositive, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Quantity must be positive."),
        D(FulfillmentErrorCodes.StatusTerminal, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Fulfillment is in a terminal status."),
        D(FulfillmentErrorCodes.StatusProcessingInvalid, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Processing status transition is invalid."),
        D(FulfillmentErrorCodes.SelectionRequired, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "A selection is required."),
        D(FulfillmentErrorCodes.OutboxUnmappedEvent, ErrorClassification.Platform, StatusCodes.Status503ServiceUnavailable,
            "Fulfillment outbox event has no mapping."),
        D(FulfillmentErrorCodes.ProcessingQuantityExceeds, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Processing quantity exceeds the sellable amount."),
        D(FulfillmentErrorCodes.ProcessingQuantityPositive, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Processing quantity must be positive."),
        D(FulfillmentErrorCodes.ProcessingReleaseInvalid, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Processing release is invalid."),
        D(FulfillmentErrorCodes.ProcessingReleaseQuantityPositive, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Processing release quantity must be positive."),
        D(FulfillmentErrorCodes.ProcessAfterDelivered, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Cannot process after delivery."),
        D(FulfillmentErrorCodes.UnconfirmAlreadyStarted, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Cannot unconfirm a started fulfillment."),
        D(FulfillmentErrorCodes.PackQuantityExceeds, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Packing quantity exceeds the processed amount."),
        D(FulfillmentErrorCodes.PackQuantityPositive, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Packing quantity must be positive."),
        D(FulfillmentErrorCodes.PackReleaseExceeds, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Release exceeds the packed amount."),
        D(FulfillmentErrorCodes.PackReleaseQuantityPositive, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Release quantity must be positive."),
        D(FulfillmentErrorCodes.PackReleaseAllocated, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Cannot release an already allocated line."),
        D(FulfillmentErrorCodes.PackRequiresProcessing, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Packing requires the line to be processed first."),
        D(FulfillmentErrorCodes.PackAfterDelivered, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Cannot pack after delivery."),
        D(FulfillmentErrorCodes.ShipQuantityExceeds, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Ship quantity exceeds the packed amount."),
        D(FulfillmentErrorCodes.ShipQuantityPositive, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Ship quantity must be positive."),
        D(FulfillmentErrorCodes.CancelAlreadyDispatched, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Cannot cancel an already dispatched fulfillment."),
        D(FulfillmentErrorCodes.RestoreAlreadyDispatched, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Cannot restore an already dispatched fulfillment."),
        D(FulfillmentErrorCodes.ShipmentNotFound, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Shipment was not found."),
        D(FulfillmentErrorCodes.ShipmentQuantityExceedsOrdered, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Shipment quantity exceeds the ordered amount."),
        D(FulfillmentErrorCodes.ShipmentQuantityExceedsPacked, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Shipment quantity exceeds the packed amount."),
        D(FulfillmentErrorCodes.ShipmentCancelInvalid, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Shipment cancellation is invalid in this state."),
        D(FulfillmentErrorCodes.ShipmentCarrierRequired, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Carrier display name is required."),
        D(FulfillmentErrorCodes.ShipmentCreateTerminal, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Cannot create a shipment for a terminal fulfillment."),
        D(FulfillmentErrorCodes.ShipmentLockedByConsolidatedPackage, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Shipment is locked by a consolidated package."),
        D(FulfillmentErrorCodes.DispatchInvalidStatus, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Dispatch is invalid in this state."),
        D(FulfillmentErrorCodes.DispatchTrackingRequired, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Dispatch requires a tracking reference."),
        D(FulfillmentErrorCodes.DeliverInvalidStatus, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Delivery is invalid in this state."),
        D(FulfillmentErrorCodes.TrackingRequired, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Tracking reference is required."),
        D(FulfillmentErrorCodes.TrackingAlreadySet, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Tracking reference was already set."),
        D(FulfillmentErrorCodes.TrackingDuplicate, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Duplicate tracking reference."),
        D(FulfillmentErrorCodes.TrackingInvalidState, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Tracking state does not allow this change."),
        D(FulfillmentErrorCodes.TrackingLockedAfterDispatch, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Tracking is locked after dispatch."),
        D(FulfillmentErrorCodes.TrackingNothingToCorrect, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "There is nothing to correct on the tracking reference."),
        D(FulfillmentErrorCodes.PackageNotFound, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Consolidated package was not found."),
        D(FulfillmentErrorCodes.PackageRequiresMultiSeller, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Consolidation requires multiple sellers."),
        D(FulfillmentErrorCodes.PackageMixedCheckout, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Consolidation cannot span checkouts."),
        D(FulfillmentErrorCodes.PackageCheckoutRequired, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Checkout is required for consolidation."),
        D(FulfillmentErrorCodes.PackageShippingMethodRequired, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Shipping method is required for consolidation."),
        D(FulfillmentErrorCodes.PackageShippingMethodMismatch, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Consolidated members must share one shipping method."),
        D(FulfillmentErrorCodes.PackageShipmentAlreadyMember, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Shipment is already a package member."),
        D(FulfillmentErrorCodes.PackageShipmentNotEligible, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Shipment is not eligible for consolidation."),
        D(FulfillmentErrorCodes.PackageDuplicateShipment, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Duplicate shipment in the package."),
        D(FulfillmentErrorCodes.PackageMemberStateChanged, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Package member state changed underneath the operation."),
        D(FulfillmentErrorCodes.PackageDispatchInvalidState, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Package dispatch is invalid in this state."),
        D(FulfillmentErrorCodes.PackageDeliverBeforeDispatch, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Package cannot be delivered before dispatch."),
        D(FulfillmentErrorCodes.PackageCancelAfterDispatch, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Package cannot be cancelled after dispatch."),
        D(FulfillmentErrorCodes.PackageTrackingLocked, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Package tracking is locked."),
        D(FulfillmentErrorCodes.PackageTrackingRequired, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Package tracking is required."),
        D(FulfillmentErrorCodes.ShippingMethodUnsupported, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Shipping method is unsupported."),
        D(FulfillmentErrorCodes.ShippingPostRecipientRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Post provider requires a recipient name."),
        D(FulfillmentErrorCodes.ShippingPostAddressRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Post provider requires a full address."),
        D(FulfillmentErrorCodes.ShippingPostalInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Postal code is invalid."),
        D(FulfillmentErrorCodes.ShippingTipaxAddressRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Tipax provider requires a full address."),
        D(FulfillmentErrorCodes.ShippingCourierAddressRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Courier provider requires a full address."),
        D(FulfillmentErrorCodes.ShippingPickupLocationRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Pickup provider requires a location."),
        D(FulfillmentErrorCodes.ShippingMobileInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Mobile number is invalid."),
        D(FulfillmentErrorCodes.SellerOrderHandleDenied, ErrorClassification.Forbidden, StatusCodes.Status403Forbidden,
            "Seller lacks order.handle permission."),
        D(FulfillmentErrorCodes.SellerOrderHandleScopeDenied, ErrorClassification.Forbidden, StatusCodes.Status403Forbidden,
            "Order.handle category scope does not cover all lines."),
        // seller.order.missing / customer.order.missing descriptors are owned by
        // OrderErrorCatalogContributor (Order owns the order aggregate and the seller.*/customer.* keyspace);
        // Fulfillment consumes the codes via FulfillmentErrorCodes without re-registering the descriptor.
        D(FulfillmentErrorCodes.CustomerActorMissing, ErrorClassification.Forbidden, StatusCodes.Status401Unauthorized,
            "Customer actor is missing."),
        D(FulfillmentErrorCodes.WorkQueueBulkFailed, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Fulfillment work-queue bulk operation failed."),
        D(FulfillmentErrorCodes.WorkQueueBulkUnsupported, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Fulfillment work-queue bulk action is unsupported."),
        D(FulfillmentErrorCodes.WorkQueueBulkEmpty, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Fulfillment work-queue bulk selection is empty."),
        D(FulfillmentErrorCodes.WorkQueueCrossSeller, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Fulfillment work-queue bulk cannot span sellers."),
        D(FulfillmentErrorCodes.WorkQueueRowMismatch, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Fulfillment work-queue row does not match server state."),
        D(FulfillmentErrorCodes.WorkQueueIncompatible, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Fulfillment work-queue bulk selection is incompatible."),
        D(FulfillmentErrorCodes.WorkQueueShipmentMissing, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Fulfillment work-queue shipment is missing."),
        D(FulfillmentErrorCodes.ShippingServiceNotFound, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Shipping service was not found."),
        D(FulfillmentErrorCodes.ShippingServiceCodeDuplicate, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Shipping service code already exists."),
        D(FulfillmentErrorCodes.ShippingServiceCodeRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Shipping service code is required."),
        D(FulfillmentErrorCodes.ShippingServiceNameRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Shipping service name is required."),
        D(FulfillmentErrorCodes.ShippingServiceLanguageInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Shipping service language is invalid."),
        D(FulfillmentErrorCodes.ShippingServiceOptionCodeRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Shipping service option code is required."),
        D(FulfillmentErrorCodes.ShippingServiceOptionNameRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Shipping service option name is required."),
    ];

    private static ErrorDescriptor D(
        string code,
        ErrorClassification classification,
        int status,
        string fallback) =>
        new(code, classification, status, code, ErrorSeverity.Warning, fallback);
}
