<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <RootNamespace>Tooba.Settlement.Application</RootNamespace>
    <AssemblyName>Tooba.Settlement.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Tooba.Settlement.Contracts\Tooba.Settlement.Contracts.csproj" />
    <ProjectReference Include="..\Tooba.Settlement.Domain\Tooba.Settlement.Domain.csproj" />
    <ProjectReference Include="..\..\Party\Tooba.Party.Contracts\Tooba.Party.Contracts.csproj" />
  </ItemGroup>
</Project>
