<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.Promotion.Contracts</RootNamespace>
    <AssemblyName>Tooba.Promotion.Contracts</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\PromotionErrors.resx">
      <LogicalName>Tooba.Promotion.Contracts.Resources.PromotionErrors.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PromotionErrors.fa.resx">
      <LogicalName>Tooba.Promotion.Contracts.Resources.PromotionErrors.fa.resources</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
