// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tooba.Support.Infrastructure.Persistence;

#nullable disable

namespace Tooba.Support.Infrastructure.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    [Migration("20260827120000_InitialSupport")]
    partial class InitialSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("support")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
modelBuilder.Entity("Tooba.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("edition");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "support");
                });

            modelBuilder.Entity("Tooba.Support.Domain.SupportTicket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid?>("AssignedOperatorActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_operator_actor_user_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("related_entity_type");

                    b.Property<Guid>("RequesterActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_actor_user_id");

                    b.Property<string>("RequesterKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("requester_kind");

                    b.Property<Guid?>("RequesterPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_party_id");

                    b.Property<Guid?>("SellerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_party_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TicketId")
                        .HasName("pk_support_tickets");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_support_tickets_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("RequesterActorUserId", "CreatedAt")
                        .HasDatabaseName("ix_support_tickets_requester_actor_user_id_created_at");

                    b.HasIndex("SellerPartyId", "CreatedAt")
                        .HasDatabaseName("ix_support_tickets_seller_party_id_created_at");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_support_tickets_status_updated_at");

                    b.ToTable("support_tickets", "support");
                });

            modelBuilder.Entity("Tooba.Support.Domain.TicketMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("AuthorActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_actor_user_id");

                    b.Property<string>("AuthorKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("author_kind");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsInternalNote")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal_note");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("MessageId")
                        .HasName("pk_ticket_messages");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_messages_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_messages_ticket_id_created_at");

                    b.ToTable("ticket_messages", "support");
                });

#pragma warning restore 612, 618
        }
    }
}
