<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Tooba.Notification.Tests</RootNamespace>
    <AssemblyName>Tooba.Notification.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
    <ItemGroup>
    <ProjectReference Include="..\Tooba.Notification.Domain\Tooba.Notification.Domain.csproj" />
    <ProjectReference Include="..\Tooba.Notification.Application\Tooba.Notification.Application.csproj" />
    <ProjectReference Include="..\Tooba.Notification.Contracts\Tooba.Notification.Contracts.csproj" />
    <ProjectReference Include="..\Tooba.Notification.Infrastructure\Tooba.Notification.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Order\Tooba.Order.Contracts\Tooba.Order.Contracts.csproj" />
  </ItemGroup>
</Project>
