<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.StoreContext.Infrastructure</RootNamespace>
    <AssemblyName>Tooba.StoreContext.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tooba.StoreContext.Contracts\Tooba.StoreContext.Contracts.csproj" />
    <ProjectReference Include="..\..\Tooba.ModuleContracts\Tooba.ModuleContracts.csproj" />
  </ItemGroup>
</Project>
