<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.Cart.Endpoints</RootNamespace>
    <AssemblyName>Tooba.Cart.Endpoints</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tooba.Cart.Application\Tooba.Cart.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Tooba.BuildingBlocks\Tooba.BuildingBlocks.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\CartErrors.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>CartErrors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CartErrors.fa.resx">
      <DependentUpon>CartErrors.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>
