<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tooba.Wallet.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tooba.Wallet.Domain\Tooba.Wallet.Domain.csproj" />
    <ProjectReference Include="..\Tooba.Wallet.Contracts\Tooba.Wallet.Contracts.csproj" />
  </ItemGroup>
</Project>
