// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tooba.Localization.Infrastructure.Persistence;

#nullable disable

namespace Tooba.Localization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LocalizationDbContext))]
    [Migration("20260901220000_InitialLocalization")]
    partial class InitialLocalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) =>
            LocalizationDbContextModelSnapshot.BuildLocalizationModel(modelBuilder);
    }
}
