using Microsoft.AspNetCore.Http;
using Tooba.BuildingBlocks.Presentation.Errors;
using Tooba.Catalog.Contracts.Errors;

namespace Tooba.Catalog.Endpoints.Errors;

/// <summary>Canonical Catalog error catalog contributor.</summary>
public sealed class CatalogErrorCatalogContributor : IErrorCatalogContributor
{
    /// <inheritdoc />
    public IReadOnlyList<ErrorDescriptor> Contribute() =>
    [
        D(CatalogErrorCodes.QuantityRoundingInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Quantity rounding mode is invalid."),
        D(CatalogErrorCodes.UnitMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Unit of measure was not found."),
        D(CatalogErrorCodes.UnitDimensionInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Unit dimension is invalid."),
        D(CatalogErrorCodes.UnitCodeDuplicate, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Unit code already exists."),
        D(CatalogErrorCodes.UnitLanguageUnknown, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Unit translation language is unknown."),
        D(CatalogErrorCodes.TagInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Tag input is invalid."),
        D(CatalogErrorCodes.TagCodeDuplicate, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Tag code already exists."),
        D(CatalogErrorCodes.TagMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Tag was not found."),
        D(CatalogErrorCodes.TagAssignDuplicate, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Tag is already assigned."),
        D(CatalogErrorCodes.TagProductMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Product was not found for tag assignment."),
        D(CatalogErrorCodes.TagCategoryMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Category was not found for tag assignment."),
        D(CatalogErrorCodes.MegaMenuCategoryMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Category was not found for MegaMenu."),
        D(CatalogErrorCodes.MegaMenuPlacementInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "MegaMenu placement is invalid."),
        D(CatalogErrorCodes.MegaMenuRemoveHasChildren, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "MegaMenu item still has presentation children."),
        D(CatalogErrorCodes.FacetCategoryMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Category was not found for Facet."),
        D(CatalogErrorCodes.FacetDefinitionMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Attribute definition was not found for Facet."),
        D(CatalogErrorCodes.FacetSchemaMissing, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Attribute is not in the category effective schema."),
        D(CatalogErrorCodes.FacetNotFilterable, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Only filterable attributes may be configured as facets."),
        D(CatalogErrorCodes.FacetDisplayTypeInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Facet display type is invalid for the attribute value kind."),
        D(CatalogErrorCodes.FacetOverrideMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Local facet override was not found."),
        D(CatalogErrorCodes.FacetReorderInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Facet reorder list must match the local configuration set exactly."),
        D(CatalogErrorCodes.CategoryMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Category was not found."),
        D(CatalogErrorCodes.CategoryInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Category input is invalid."),
        D(CatalogErrorCodes.CategorySlugInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Category slug is invalid."),
        D(CatalogErrorCodes.CategorySlugDuplicate, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Category slug is already in use for this locale."),
        D(CatalogErrorCodes.CategoryParentMissing, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Parent category was not found."),
        D(CatalogErrorCodes.CategorySelfParent, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Category cannot be its own parent."),
        D(CatalogErrorCodes.CategoryDescendantParent, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Category cannot be moved under its own descendant."),
        D(CatalogErrorCodes.CategoryMaxDepth, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Category hierarchy exceeds maximum depth."),
        D(CatalogErrorCodes.CategoryReorderInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Category reorder list must match the sibling set exactly."),
        D(CatalogErrorCodes.CategoryConcurrencyConflict, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Category was modified concurrently."),
        D(CatalogErrorCodes.CategoryRouteInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Category route resolve input is invalid."),
        D(CatalogErrorCodes.CategoryRouteMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Category route was not found."),
        D(CatalogErrorCodes.AttributeMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Attribute definition was not found."),
        D(CatalogErrorCodes.AttributeInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Attribute definition input is invalid."),
        D(CatalogErrorCodes.AttributeCodeDuplicate, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Attribute definition code already exists."),
        D(CatalogErrorCodes.AttributeNameDuplicate, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "An attribute with this localized name already exists."),
        D(CatalogErrorCodes.AttributeVariantAxisValueKindInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "This value kind cannot be used as a variant axis."),
        D(CatalogErrorCodes.AttributeVariantAxisInUse, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "This attribute is used by active variant axes."),
        D(CatalogErrorCodes.AttributeVariantAxisCapabilityDisabled, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Variant-axis capability is not enabled on this definition."),
        D(CatalogErrorCodes.SchemaCategoryMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Category was not found for attribute-schema."),
        D(CatalogErrorCodes.SchemaBindingDuplicate, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "This attribute is already bound to the category."),
        D(CatalogErrorCodes.SchemaBindingMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Category attribute binding was not found."),
        D(CatalogErrorCodes.SchemaReorderInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Schema reorder list must match the local binding set exactly."),
        D(CatalogErrorCodes.SchemaInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Category attribute-schema input is invalid."),
        D(CatalogErrorCodes.ProductMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Product was not found."),
        D(CatalogErrorCodes.AttributeDefinitionInactive, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Attribute definition is inactive."),
        D(CatalogErrorCodes.AttributeSchemaNotAllowed, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Attribute is not allowed by the product effective schema."),
        D(CatalogErrorCodes.AttributeVariantAxisOnProductForbidden, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Variant-axis attributes cannot be stored on the product."),
        D(CatalogErrorCodes.AttributeEnumOptionRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Enumeration option id is required."),
        D(CatalogErrorCodes.AttributeEnumOptionMismatch, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Enumeration option does not belong to this definition."),
        D(CatalogErrorCodes.AttributeEnumOptionInactive, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Enumeration option is inactive."),
        D(CatalogErrorCodes.AttributeEnumOptionInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Enumeration option payload is invalid."),
        D(CatalogErrorCodes.AttributeValueInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Attribute value is invalid."),
        D(CatalogErrorCodes.AttributeValidationBounds, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Attribute value violates definition bounds."),
        D(CatalogErrorCodes.AttributeClearRequiredForbidden, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Clearing a required attribute is not allowed."),
        D(CatalogErrorCodes.AttributeValueEmpty, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Attribute value is empty."),
        D(CatalogErrorCodes.VariantAxesDuplicate, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Product variant axes must not contain duplicates."),
        D(CatalogErrorCodes.VariantAxisSchemaNotEnabled, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Variant axis is not enabled in the effective category schema."),
        D(CatalogErrorCodes.VariantEffectiveAxesMissing, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "No effective variant axes are available for this product."),
        D(CatalogErrorCodes.VariantCombinationLimitExceeded, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Variant combination count exceeds the safe limit."),
        D(CatalogErrorCodes.VariantPatchTargetMissing, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Variant patch target was not found on the product."),
        D(CatalogErrorCodes.VariantPatchStatusInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Variant patch status is invalid."),
        D(CatalogErrorCodes.VariantDefaultMissing, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Default variant was not found on the product."),
        D(CatalogErrorCodes.VariantArchivedCannotBeDefault, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "An archived variant cannot be the default."),
        D(CatalogErrorCodes.CategoryAssignmentLevelInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Product must be assigned to a Level-3 category."),
        D(CatalogErrorCodes.CategoryChangeInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Category change is invalid."),
        D(CatalogErrorCodes.WorkspaceProductMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Product was not found."),
        D(CatalogErrorCodes.WorkspacePermissionDenied, ErrorClassification.Forbidden, StatusCodes.Status403Forbidden,
            "Forbidden"),
        D(CatalogErrorCodes.WorkspaceMediaAssetMissing, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Media asset id is required."),
        D(CatalogErrorCodes.WorkspaceMediaAttachRejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Media attach was rejected."),
        D(CatalogErrorCodes.WorkspaceMediaPlaceholderRejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Placeholder media was rejected."),
        D(CatalogErrorCodes.WorkspaceMediaEmpty, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Product has no media."),
        D(CatalogErrorCodes.WorkspaceMediaOrderInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Media order list is invalid."),
        D(CatalogErrorCodes.WorkspaceMediaOrderRejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Media reorder was rejected."),
        D(CatalogErrorCodes.WorkspaceMediaMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Media reference was not found on the product."),
        D(CatalogErrorCodes.WorkspaceCatalogStale, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Catalog data is stale."),
        D(CatalogErrorCodes.WorkspaceProductSlugDuplicate, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Product slug is already in use."),
        D(CatalogErrorCodes.WorkspaceProductSlugInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Product slug is invalid."),
        D(CatalogErrorCodes.WorkspaceProductSeoRejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Product SEO update was rejected."),
        D(CatalogErrorCodes.WorkspaceProductPublishRejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Product publish was rejected."),
        D(CatalogErrorCodes.WorkspaceProductUnpublishRejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Product unpublish was rejected."),
        D(CatalogErrorCodes.WorkspaceProductArchiveRejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Product archive was rejected."),
        D(CatalogErrorCodes.WorkspaceProductRestoreRejected, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Product restore was rejected."),
        D(CatalogErrorCodes.CheckoutAbuseInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Checkout abuse settings input is invalid."),
        D(CatalogErrorCodes.CheckoutAbuseMaxOpenUnpaidInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Max open unpaid orders value is invalid."),
        D(CatalogErrorCodes.CheckoutAbuseWindowInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Reservation commit window value is invalid."),
        D(CatalogErrorCodes.CheckoutAbuseMaxCommitsInvalid, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Max checkout commits value is invalid."),
        D(CatalogErrorCodes.LandingPageMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Landing page was not found."),
        D(CatalogErrorCodes.MenuMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Store menu was not found."),
        D(CatalogErrorCodes.MenuTitleRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Menu title is required."),
        D(CatalogErrorCodes.MenuKeyRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Menu key is required."),
        D(CatalogErrorCodes.MenuKeyDuplicate, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Menu key already exists."),
        D(CatalogErrorCodes.MenuDeleteReferenced, ErrorClassification.Conflict, StatusCodes.Status409Conflict,
            "Menu is still referenced."),
        D(CatalogErrorCodes.MenuItemMissing, ErrorClassification.NotFound, StatusCodes.Status404NotFound,
            "Menu item was not found."),
        D(CatalogErrorCodes.MenuItemLabelRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Menu item label is required."),
        D(CatalogErrorCodes.MenuItemParentInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Menu item parent is invalid."),
        D(CatalogErrorCodes.MenuItemCycle, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Menu item cycle is not allowed."),
        D(CatalogErrorCodes.MenuItemDepth, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Menu item depth exceeded."),
        D(CatalogErrorCodes.MenuItemReorderInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Menu item reorder list is incomplete."),
        D(CatalogErrorCodes.MenuLinkInvalid, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Menu link type is invalid."),
        D(CatalogErrorCodes.MenuUrlRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "External URL is required."),
        D(CatalogErrorCodes.MenuUrlUnsafe, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "External URL is not allowed."),
        D(CatalogErrorCodes.MenuTargetRequired, ErrorClassification.Validation, StatusCodes.Status400BadRequest,
            "Menu target is required."),
        D(CatalogErrorCodes.MenuTargetMissing, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Menu target was not found in this store."),
        D(CatalogErrorCodes.MenuHeaderIneligible, ErrorClassification.Business, StatusCodes.Status400BadRequest,
            "Only an enabled menu can be selected as header."),
    ];

    private static ErrorDescriptor D(
        string code,
        ErrorClassification classification,
        int status,
        string fallback) =>
        new(
            Code: code,
            Classification: classification,
            HttpStatus: status,
            LocalizationKey: code,
            Severity: ErrorSeverity.Warning,
            SafeTitleFallback: fallback);
}
