// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tooba.Promotion.Infrastructure.Persistence;

#nullable disable

namespace Tooba.Promotion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    [Migration("20260919134400_MerchandisingCampaignFoundation")]
    partial class MerchandisingCampaignFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("promotion")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tooba.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("edition");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "promotion");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_status");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("PromotionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_type_id");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_merchandising_campaigns");

                    b.HasIndex("PromotionTypeId")
                        .HasDatabaseName("ix_merchandising_campaigns_promotion_type_id");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_merchandising_campaigns_store_id");

                    b.HasIndex("StoreId", "Priority")
                        .HasDatabaseName("ix_merchandising_campaigns_store_id_priority");

                    b.HasIndex("LifecycleStatus", "StartAt", "EndAt")
                        .HasDatabaseName("ix_merchandising_campaigns_lifecycle_status_start_at_end_at");

                    b.HasIndex("StoreId", "PromotionTypeId", "LifecycleStatus")
                        .HasDatabaseName("ix_merchandising_campaigns_store_id_promotion_type_id_lifecycl");

                    b.ToTable("merchandising_campaigns", "promotion");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingCampaignOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SellerOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_offer_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_merchandising_campaign_offers");

                    b.HasIndex("SellerOfferId")
                        .HasDatabaseName("ix_merchandising_campaign_offers_seller_offer_id");

                    b.HasIndex("CampaignId", "SellerOfferId")
                        .IsUnique()
                        .HasDatabaseName("ix_merchandising_campaign_offers_campaign_id_seller_offer_id");

                    b.HasIndex("CampaignId", "SortOrder")
                        .HasDatabaseName("ix_merchandising_campaign_offers_campaign_id_sort_order");

                    b.ToTable("merchandising_campaign_offers", "promotion");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingCampaignTranslation", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Locale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("locale");

                    b.Property<string>("BadgeText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("badge_text");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("CampaignId", "Locale")
                        .HasName("pk_merchandising_campaign_translations");

                    b.ToTable("merchandising_campaign_translations", "promotion");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingPromotionType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_merchandising_promotion_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_merchandising_promotion_types_code");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("ix_merchandising_promotion_types_is_active_sort_order");

                    b.ToTable("merchandising_promotion_types", "promotion");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingPromotionTypeTranslation", b =>
                {
                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<string>("Locale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("locale");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.HasKey("TypeId", "Locale")
                        .HasName("pk_merchandising_promotion_type_translations");

                    b.ToTable("merchandising_promotion_type_translations", "promotion");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.PromotionDefinition", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<Guid?>("CatalogVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_variant_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_party_id");

                    b.Property<string>("DiscountKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("discount_kind");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("FixedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fixed_amount");

                    b.Property<string>("FixedAmountCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("fixed_amount_currency");

                    b.Property<string>("Market")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("market");

                    b.Property<int?>("MinimumQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_quantity");

                    b.Property<decimal?>("MinimumSubtotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("minimum_subtotal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid?>("OrganizationPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_party_id");

                    b.Property<decimal>("PercentageRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("percentage_rate");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("SalesChannel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sales_channel");

                    b.Property<Guid?>("SellerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_party_id");

                    b.Property<string>("StackingPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stacking_policy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PromotionId")
                        .HasName("pk_promotions");

                    b.HasIndex("CouponCode")
                        .HasDatabaseName("ix_promotions_coupon_code");

                    b.HasIndex("Status", "EffectiveFrom")
                        .HasDatabaseName("ix_promotions_status_effective_from");

                    b.ToTable("promotions", "promotion");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingCampaign", b =>
                {
                    b.HasOne("Tooba.Promotion.Domain.MerchandisingPromotionType", null)
                        .WithMany()
                        .HasForeignKey("PromotionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_merchandising_campaigns_merchandising_promotion_types_promo");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingCampaignOffer", b =>
                {
                    b.HasOne("Tooba.Promotion.Domain.MerchandisingCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merchandising_campaign_offers_merchandising_campaigns_campa");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingCampaignTranslation", b =>
                {
                    b.HasOne("Tooba.Promotion.Domain.MerchandisingCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merchandising_campaign_translations_merchandising_campaigns");
                });

            modelBuilder.Entity("Tooba.Promotion.Domain.MerchandisingPromotionTypeTranslation", b =>
                {
                    b.HasOne("Tooba.Promotion.Domain.MerchandisingPromotionType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merchandising_promotion_type_translations_merchandising_pro");
                });
#pragma warning restore 612, 618
        }
    }
}
